config/routes.rb
Rails.application.routes.draw do  
  get 'pages/index'
  # http://railscasts.com/episodes/350-rest-api-versioning?view=asciicast
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :regions, only: %i[index show] do
        collection do
          get 'geo'
          get 'country'
          get 'states'     
          get 'validate'     
        end
      end
    end
  end
  
  root to: 'pages#index'
  get '/about', to: 'pages#about', as: :about
  get '/postcode', to: 'pages#about', as: :postcode
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ActiveHash::Base
  include ActiveHash::Associations
  has_many :states
  
  self.data = [
    {
      :id => 1, 
      :name => "Montenegro", 
      :code => "me", 
      :country_code => "382",
      :currency_code => "EUR",
      :latitude => "42.708678",
      :latitude_dec => "42.752803802490234",
      :longitude => "19.37439",
      :longitude_dec => "19.237918853759766",
      :max_latitude => "43.558743",
      :max_longitude => "20.3574869",
      :min_latitude => "41.8297",
      :min_longitude => "18.4337921"
    }
  ]
  
  def geo
    {
      latitude: self.latitude,
      latitude_dec: self.latitude_dec,
      longitude: self.longitude,
      longitude_dec: self.longitude_dec,
      max_latitude: self.max_latitude,
      max_longitude: self.max_longitude,
      min_latitude: self.min_latitude,
      min_longitude: self.min_longitude,
    }
  end
end

app/models/state.rb
class State < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :country
  has_many :subdivisions
  
  scope :search, -> (term) {
    where("LOWER(name) LIKE :term", term: "%#{term.downcase}%")
  }
  
  def geo
    {
      latitude: self.latitude,
      longitude: self.longitude,
      max_latitude: self.max_latitude,
      max_longitude: self.max_longitude,
      min_latitude: self.min_latitude,
      min_longitude: self.min_longitude,
    }
  end    
end

app/models/subdivision.rb
class Subdivision < ApplicationRecord
  belongs_to :state
end

app/controllers/api/v1/regions_controller.rb
# app/controllers/api/v1/regions_controller.rb
module Api
  class V1::RegionsController < ApiController
    before_action :set_country
    
    def index
      response = { message: "Index for API regions method" }
      render json: response
    end
  
    def show
      response = { message: "Show for API regions method" }
      render json: response      
    end
    
    def geo
      # api_url = "https://nominatim.openstreetmap.org/search?country=montenegro&postalcode=85340&addressdetails=1&format=json"
      
      api_url = "https://nominatim.openstreetmap.org/search?country=Montenegro&format=geojson"
      #response = HTTParty.get(api_url)
      response = JSON.parse(RestClient.get(api_url))
      render json: response
    end

    # GET
    # /api/v1/regions/country/?id=1
    # /api/v1/regions/country/?code=ME
    # /api/v1/regions/country (or add ?code=COUNTRY_ISO_CODE)
    def country      
      response = CountryPresenter.new(@country)
      render json: response.result
    end
    
    # GET
    # /api/v1/regions/states/?name=StateName
    # /api/v1/regions/states (or add ?name=StateName)
    def states
      response = params[:name].present? ? State.search(params[:name].to_s) : @country.states
      render json: response
    end
    

    # GET
    # /api/v1/regions/validate/:postcode
    def validate
      zipcode = Subdivision.where(postcode: params[:postcode]).take
      
      if zipcode.present?
        response = { status: :ok, message: "Postcode found", result: zipcode }
      else
        response = { status: :not_found, message: "Postcode not found" }
      end
      
      render json: response
    end
        
    private
    
    def set_country
      @country = params[:id].present? ? Country.find(params[:id]) : Country.first
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def about
  end
  
  def postcode
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Montenegro API - Free Postcode Validation Service</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- JavaScript and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  </head>

  <body id="montenegro_api" class="">
    <%= render "shared/navbar" %>
    
    <div id="content" class="container">
        <%= yield %>
    </div>
    
    <footer class="container-fluid bg-light text-center mt-5 p-2">
      <p class="font-weight-light text-muted mt-2">
        Brought you by <a href="https://rubydroids.com" class="text-reset">RubyDroids Co</a>. Star this project at 
        <a href="#" class=text-reset>
          Github
          <i class="fab fa-github ml-1"></i>
        </a>
      </p>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-5 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Free API for Regions in Montenegro</h5>
        
        <p class="card-text">This is an open-source project. Using this RESTful API service you can validate Postcode (Zipcode) in Montenegro. It's free and available for everyone who need to validate zipcode, get districts information and other regional data.</p>
        
        <p class="card-text">Example of use: in shopping cart of eCommerce. Just point to us and validate typed by user postcode.</p>
        
        <%= root_url[0...-1] + country_api_v1_regions_path %>
        
        <pre class="mt-2">
          <code lang="ruby">
# Get all information about country
RestClient.get('http://localhost:3001/api/v1/regions/country/?id=1')

# =>
{
  "name":"Montenegro",
  "country_code":"382",
  "currency_code":"EUR",
  "geo": {
    "latitude":"42.708678",
    "latitude_dec":"42.752803802490234",
    "longitude":"19.37439",
    "longitude_dec":"19.237918853759766",
    "max_latitude":"43.558743",
    "max_longitude":"20.3574869",
    "min_latitude":"41.8297",
    "min_longitude":"18.4337921"
  }
}
          </code>
        </pre>
        
        <a href="#" class="btn btn-secondary mt20">Get your credentials</a>
      </div>
    </div>
  </div>
  <div class="col-12 col-sm-12 col-md-12 col-lg-7 mb-4">
    <iframe 
      width="100%" 
      height="550" 
      frameborder="0" 
      scrolling="no" 
      marginheight="0" 
      marginwidth="0"
          src="https://www.openstreetmap.org/export/embed.html?bbox=16.660766601562504%2C41.35207214451295%2C20.742187500000004%2C43.94537239244211&amp;layer=mapnik" 
  style="border: 1px solid dimedgray">
  </iframe>
  <p class="text-right"> 
    <small>
      <a href="https://www.openstreetmap.org/#map=8/42.662/18.701" class="link-secondary">See a bigger map</a>
    </small>
  </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to "Montenegro API", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarMenu" style="">
      <ul class="navbar-nav mr-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "Postcode Validation", postcode_path, class: "nav-link" %>
        </li>
      </ul>
      
      <div class="d-flex">
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">
          <li class="nav-item">
            <%= link_to "postcode_path", class: "nav-link" do %>
              <%= "Free Access" %>
              <i class="fas fa-user-tie ml-2 pb-1"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>